application: miniproject1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /manage
  script: handlers.manage_handler.app

- url: /delete_streams
  script: handlers.manage_handler.app
  login: required

- url: /unsubscribe_streams
  script: handlers.manage_handler.app
  login: required

- url: /create_stream
  script: handlers.create_stream_handler.app
  login: required

- url: /create
  script: handlers.create_stream_handler.app
  login: required

- url: /stream.*
  script: handlers.view_single_stream_handler.app
  login: required

- url: /upload
  script: handlers.view_single_stream_handler.app
  login: required

- url: /img.*
  script: handlers.view_single_stream_handler.app
  login: required

- url: /show_more.*
  script: handlers.view_single_stream_handler.app
  login: required

- url: /subscribe_stream
  script: handlers.view_single_stream_handler.app
  login: required

- url: /unsubscribe_stream
  script: handlers.view_single_stream_handler.app
  login: required

- url: /delete_photos
  script: handlers.view_single_stream_handler.app
  login: required

- url: /geo_data
  script: handlers.view_single_stream_handler.app
  login: required

- url: /view_all_stream
  script: handlers.view_all_streams_handler.app
  login: required

- url: /search_streams
  script: handlers.search_handler.app
  login: required

- url: /show_result
  script: handlers.search_handler.app
  login: required

- url: /auto_complete
  script: handlers.search_handler.app
  login: required

- url: /rebuild_search_index
  script: handlers.search_handler.app

- url: /trending_stream
  script: handlers.trending_handler.app
  login: required

- url: /update_email_freq
  script: handlers.trending_handler.app
  login: required

- url: /send_email
  script: handlers.trending_handler.app

- url: /clear
  script: handlers.trending_handler.app

- url: /
  script: handlers.login.app

- url: /error
  script: handlers.error.app

- url: /.*
  script: handlers.error.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest